eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    preferIpAddress: true
    service-url:
      defaultZone: http://alert-job-eureka:8012/eureka
  instance:
    prefer-ip-address: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://alert-job-keycloak:8080/realms/myrealm/protocol/openid-connect/certs
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://alert-job-keycloak:8080/realms/myrealm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: client-test-service
            client-secret: 0T1oDiRDnb18geE1KvD9KSVX6eBlV2AD
            authorization-grant-type: authorization_code
            redirect-uri: http://alert-job-keycloak:8080/login/oauth2/code/keycloak
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes:
        - id: test-service
          uri: http://alert-job-test-service:8013
          predicates:
            - Path=/secure/**

# Enable these to debug the Authorization flow
logging:
    level:
      org:
        springframework:
          security:
            web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
