eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    preferIpAddress: true
    service-url:
      defaultZone: http://eureka:8012/eureka
  instance:
    prefer-ip-address: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://alertjob.by/keycloak/realms/myrealm/protocol/openid-connect/certs
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://alertjob.by/keycloak/realms/myrealm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: client-test-service
            client-secret: dbjPURDGArTmsjl8AJMgy0W8SKPT3eth
            authorization-grant-type: authorization_code
            redirect-uri:  http://alertjob.by/login/oauth2/code/keycloak
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay

management:
  endpoints:
    web:
      exposure:
        include: "*"
